services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-veterinaria
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - veterinaria-net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "${SONARQUBE_PORT}:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - veterinaria-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - veterinaria-net

volumes:
  mysql_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  jenkins_data:

networks:
  veterinaria-net: